### ISSUE TITLE
[Bug] Mixed use of kernel/types.h and klibc stdbool.h breaks build

### ISSUE THREAD

**Issue by vmttmv** [gbowne1/ClassicOS#91]
Mixed use of `kernel/types.h`, and `klibc/include/stdbool.h` breaks build, introduced in 785c892

Attached build log below

```
kernel/types.h:20:16: error: redeclaration of enumerator 'false'
   20 | typedef enum { false = 0, true = 1 } bool;
      |                ^~~~~
In file included from kernel/cpu.h:5,
                 from kernel/cpu.c:1:
klibc/include/stdbool.h:4:16: note: previous definition of 'false' with type 'enum <anonymous>'
    4 | typedef enum { false = 0, true = 1 } bool;
      |                ^~~~~
kernel/types.h:20:27: error: redeclaration of enumerator 'true'
   20 | typedef enum { false = 0, true = 1 } bool;
      |                           ^~~~
klibc/include/stdbool.h:4:27: note: previous definition of 'true' with type 'enum <anonymous>'
    4 | typedef enum { false = 0, true = 1 } bool;
      |                           ^~~~
kernel/types.h:20:38: error: conflicting types for 'bool'; have 'enum <anonymous>'
   20 | typedef enum { false = 0, true = 1 } bool;
      |                                      ^~~~
klibc/include/stdbool.h:4:38: note: previous declaration of 'bool' with type 'bool'
    4 | typedef enum { false = 0, true = 1 } bool;
      |                                      ^~~~
```

This stems from `kernel/types.h` and `klibc/include/stdbool.h` both defining:
`typedef enum { false = 0, true = 1 } bool`

As C11 was chosen (though C99 is identical here), the spec (`7.18  Boolean type and values<stdbool.h>`) defines `stdbool.h` as:

```
#define bool _Bool
#define true 1
#define false 0
#define __bool_true_false_are_defined 1
```
Plus header guard, and possibly wrapping the bool, false, and true macros in an `#ifdef __cplusplus`

Is `kernel/types.h` largely even necessary anymore with the introduction of `klibc`?

**Comment by gbowne1** [comment]
@vmttmv 
@shoshta73 

I think we should:

```c
#ifndef CLASSICOS_KLIBC_STDBOOL_H
#define CLASSICOS_KLIBC_STDBOOL_H

#define bool  _Bool
#define true  1
#define false 0
#define __bool_true_false_are_defined 1

#endif
```

Then in types.h

```c
// ----------------------------
// Boolean & NULL definitions
// ----------------------------
#include "klibc/include/stdbool.h"

#ifndef NULL
#define NULL ((void*)0)
#endif
```

An alternative would be to 

```c
#ifndef __bool_true_false_are_defined
  typedef enum { false = 0, true = 1 } bool;
  #define __bool_true_false_are_defined 1
#endif
```

in types.h

Theres some other ways around this.

**Comment by vmttmv** [comment]
> Then in types.h
> ...
> #ifndef NULL
> #define NULL ((void*)0)
> #endif

Is there a reason to ever redefine things in types.h rather than using `klibc/include` -headers?

**Comment by shoshta73** [comment]
`kernel/types.h` was left in to minimize possiblity of breaking builds, i think it should go now

**Comment by gbowne1** [comment]
@vmttmv
@shoshta73 

I guess we could see what happens when we remove types.c and types.c and the #include for types.h

That would probably let us know where we need klibc implementations.
